print("I am Abdellatif Maher ")
print("I am Student at Faculty of Engineering Al-Azhar University")
print("I am Student at Communication and Electronics Department")
print("3rd Year")
print("From Al-haram (Giza)")