x=input("Please Enter First Number : ")
y=input("Please Enter second Number : ")
print("First Number =",x)
print("Second Number =",y)
First_Name=input("Please Enter your First Name : ")
Second_Name=input("Please Enter your Second Name : ")
print("Welcome",First_Name,Second_Name)